// Generated by CoffeeScript 1.6.3
(function() {
  var $name, $toggle, disable, enable, handler, isRolling, names, readInterval, refresh, toggler;

  names = [];

  isRolling = false;

  $toggle = $('#btn-toggle');

  $name = $('#name');

  handler = null;

  enable = function(x) {
    return x.removeAttr('disabled');
  };

  disable = function(x) {
    return x.attr('disabled', 1);
  };

  readInterval = function() {
    var intvl;
    intvl = parseInt($('#interval').val());
    if (isNaN(intvl)) {
      intvl = 100;
    }
    return intvl;
  };

  refresh = function() {
    return $name.html(names[Math.floor(Math.random() * names.length)]);
  };

  toggler = function() {
    if (isRolling) {
      clearInterval(handler);
      isRolling = false;
      $(this).val('Start');
    } else {
      handler = setInterval(refresh, readInterval());
      isRolling = true;
      $(this).val('Stop');
    }
    return $(this).toggleClass('success').toggleClass('alert');
  };

  $(function() {
    $('.hint').delay(3000).fadeOut();
    return $('body').keypress(function(e) {
      if (e.which === 32) {
        return toggler();
      }
    });
  });

  $('#btn-init').click(function() {
    names = $('#namelist').val().split('\n').filter(function(x) {
      return x !== '';
    });
    $name.html('Ready to Go!');
    enable($toggle);
    return enable($('#btn-toggle-aside'));
  });

  $('#btn-toggle-aside').click(function() {
    return $('#aside-wrapper').fadeToggle();
  });

  $('#btn-toggle').click(toggler);

}).call(this);
